name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Install VUE Dependencies
        run: 'npm install --prefix=./src-vue/'

      - name: Build VUE
        run: 'npm run build_vue'

      - name: Install PLUGIN Dependencies
        run: 'npm install'

      - name: Build PLUGIN
        run: 'npm run build_plugin'

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}
          files: ${{ steps.package-version.outputs.current-version}}.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
